const { chromium } = require(process.env.BEELOFT_PLAYWRIGHT_MODULE || 'playwright');
const fs = require('node:fs');
const path = require('node:path');
const assert = require('node:assert/strict');
const base = process.env.BEELOFT_QA_BASE;
const work = process.env.BEELOFT_QA_WORK;
assert.ok(base && work && process.env.BEELOFT_QA_CREDENTIALS, 'Run through tests/run_browser.py with an isolated demo database.');
const creds = JSON.parse(fs.readFileSync(process.env.BEELOFT_QA_CREDENTIALS,'utf8').replace(/^\uFEFF/,''));
const admin = creds.users[0].api_key, operator = creds.users[1].api_key, viewer = creds.users[2].api_key;

(async () => {
  const browser = await chromium.launch({headless:true,channel:process.env.BEELOFT_BROWSER_CHANNEL || 'msedge'});
  const page = await browser.newPage({viewport:{width:1440,height:1000}});
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  async function login(key) {
    await page.getByLabel('Kunci akses',{exact:true}).fill(key);
    await page.getByRole('button',{name:'Buka ruang produksi',exact:true}).click();
    await page.getByRole('heading',{name:'Yang sedang dikerjakan.'}).waitFor();
    await page.locator('#summary dd').first().waitFor();
  }
  async function apiGet(url) {
    const response = await fetch(base+url,{headers:{'X-API-Key':admin}});
    assert.equal(response.status,200); return response.json();
  }
  async function apiPost(url,body,key=crypto.randomUUID()) {
    const response=await fetch(base+url,{method:'POST',headers:{'X-API-Key':admin,
      'Idempotency-Key':key,'Content-Type':'application/json'},body:JSON.stringify(body)});
    const text=await response.text();assert.equal(response.status,201,text);return JSON.parse(text);
  }
  await page.goto(base);
  await page.getByLabel('Kunci akses',{exact:true}).fill('invalid');
  await page.getByRole('button',{name:'Buka ruang produksi',exact:true}).click();
  await page.locator('#login-error:not([hidden])').waitFor();
  await login(admin);
  await page.getByRole('button',{name:'Cadangan data',exact:true}).click();
  let failBackup = true;
  await page.route('**/api/backup',async route => {
    if (failBackup) { failBackup=false; await route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({detail:'Cadangan uji belum tersedia'})}); }
    else await route.continue();
  });
  await page.getByRole('button',{name:'Unduh cadangan database',exact:true}).click();
  await page.getByText('Cadangan uji belum tersedia',{exact:true}).waitFor();
  const backupDownloadPromise=page.waitForEvent('download');
  await page.getByRole('button',{name:'Unduh cadangan database',exact:true}).click();
  const backupDownload=await backupDownloadPromise;
  assert.match(backupDownload.suggestedFilename(),/^beeloft-backup-.*\.sqlite3$/);
  const backupBytes=fs.readFileSync(await backupDownload.path());
  assert.equal(backupBytes.subarray(0,16).toString(),'SQLite format 3\x00');
  assert.ok(!backupBytes.includes(Buffer.from(admin)));
  await page.getByRole('button',{name:'Tutup dialog',exact:true}).click();
  await page.getByLabel('Status',{exact:true}).selectOption('overdue');
  await page.waitForFunction(() => document.querySelectorAll('.order-row').length === 1 && !document.getElementById('order-list').hidden);
  assert.equal((await page.locator('.order-row').innerText()).includes('DEMO-PROD-002'),true);
  await page.getByLabel('Status',{exact:true}).selectOption('all');
  await page.waitForFunction(() => document.querySelectorAll('.order-row').length === 3 && !document.getElementById('order-list').hidden);
  const globalSummary = await page.locator('#summary').innerText();
  await page.getByLabel('PIC order',{exact:true}).selectOption(creds.users[1].id);
  await page.getByLabel('Posisi barang',{exact:true}).selectOption('sewing');
  await page.waitForFunction(() => document.querySelectorAll('.order-row').length === 1 && !document.getElementById('order-list').hidden);
  assert.ok((await page.locator('.order-row').innerText()).includes('DEMO-PROD-001'));
  assert.equal(await page.locator('#summary').innerText(),globalSummary);
  await page.getByRole('button',{name:/DEMO-PROD-001/}).click();
  await page.getByRole('heading',{name:'Posisi barang sekarang'}).waitFor();
  await page.getByRole('button',{name:'Semua order',exact:false}).click();
  assert.equal(await page.getByLabel('Posisi barang',{exact:true}).inputValue(),'sewing');
  await page.getByLabel('Posisi barang',{exact:true}).selectOption('qc');
  await page.getByText('Tidak ada order yang cocok.',{exact:false}).waitFor();
  await page.getByRole('button',{name:'Reset filter',exact:true}).click();
  await page.waitForFunction(() => document.querySelectorAll('.order-row').length === 3 && !document.getElementById('order-list').hidden);
  assert.equal(await page.getByLabel('PIC order',{exact:true}).inputValue(),'');
  assert.equal(await page.getByLabel('Posisi barang',{exact:true}).inputValue(),'all');
  let failBoard = true;
  await page.route('**/api/production-board?*',async route => {
    if (failBoard) { failBoard=false; await route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({detail:'Simulasi koneksi terputus'})}); }
    else await route.continue();
  });
  await page.getByRole('button',{name:'Muat ulang',exact:true}).click();
  await page.getByText('Simulasi koneksi terputus',{exact:true}).waitFor();
  await page.getByRole('button',{name:'Muat ulang',exact:true}).click();
  await page.waitForFunction(() => !document.getElementById('order-list').hidden);
  let releaseProducts, signalProducts, finishProducts;
  const productsStarted = new Promise(resolve => signalProducts = resolve);
  const productsReleased = new Promise(resolve => releaseProducts = resolve);
  const productsFinished = new Promise(resolve => finishProducts = resolve);
  let delayProducts = true;
  await page.route('**/api/products?*', async route => {
    if (delayProducts) {
      delayProducts = false;
      const response = await route.fetch(); signalProducts();
      await productsReleased; await route.fulfill({response}); finishProducts();
    } else await route.continue();
  });
  await page.getByRole('button',{name:'Master SKU',exact:true}).click();
  await productsStarted;
  await page.getByRole('button',{name:'Tutup dialog',exact:true}).click();
  await page.getByRole('button',{name:'Buat order produksi',exact:true}).click();
  await page.getByLabel('Nama order',{exact:true}).fill('Draft must survive delayed response');
  releaseProducts(); await productsFinished;
  await page.waitForTimeout(100);
  assert.equal(await page.getByLabel('Nama order',{exact:true}).inputValue(),'Draft must survive delayed response');
  await page.getByRole('button',{name:'Tutup dialog',exact:true}).click();
  await page.screenshot({path:path.join(work,'dashboard-desktop.png'),fullPage:true});
  await page.getByLabel('Cari order atau SKU').fill('not-found');
  await page.getByRole('button',{name:'Cari order',exact:true}).click();
  await page.getByText('Tidak ada order yang cocok.',{exact:false}).waitFor();
  await page.getByLabel('Cari order atau SKU').fill('');
  await page.getByRole('button',{name:'Cari order',exact:true}).click();
  await page.locator('.order-row').first().waitFor();

  await page.getByRole('button',{name:'Master SKU',exact:true}).click();
  await page.getByRole('button',{name:'Tambah SKU',exact:true}).click();
  const unique = Date.now();
  await page.getByLabel('Kode SKU',{exact:true}).fill('DEMO-UI-'+unique);
  await page.getByLabel('Nama produk',{exact:true}).fill('CONTOH <uji teks>');
  await page.getByLabel('Warna',{exact:true}).fill('Biru');
  await page.getByLabel('Ukuran',{exact:true}).fill('L');
  await page.getByRole('button',{name:'Simpan pencatatan',exact:true}).click();
  await page.locator('dialog').waitFor({state:'hidden'});
  await page.getByRole('button',{name:'Buat order produksi',exact:true}).click();
  await page.getByLabel('Referensi order',{exact:true}).fill('DEMO-UI-ORDER-'+unique);
  await page.getByLabel('Nama order',{exact:true}).fill('CONTOH - Uji dashboard '+unique);
  await page.getByLabel('Target selesai',{exact:true}).fill('2099-01-01');
  await page.getByLabel('Jumlah',{exact:true}).fill('20');
  await page.getByRole('button',{name:'Tambah baris SKU',exact:true}).click();
  await page.getByLabel('SKU',{exact:true}).nth(1).selectOption({label:'DEMO-UI-'+unique});
  await page.getByLabel('Jumlah',{exact:true}).nth(1).fill('30');
  await page.getByRole('button',{name:'Simpan pencatatan',exact:true}).click();
  await page.getByRole('heading',{name:'CONTOH - Uji dashboard '+unique,exact:true}).waitFor();
  const board = await apiGet('/api/production-board?q=DEMO-UI-ORDER-'+unique);
  const orderId = board.orders[0].id;
  assert.equal(board.orders[0].target_quantity,50);
  await page.getByRole('button',{name:'Catat perpindahan',exact:true}).first().click();
  await page.getByLabel('Jumlah (pcs)',{exact:true}).fill('10');
  let intercepted = false, authDenied = false;
  await page.route('**/api/movements',async route => {
    if (!intercepted && route.request().method()==='POST') {
      intercepted = true; await route.fetch(); await route.abort('failed');
    } else if (!authDenied && route.request().method()==='POST') {
      authDenied = true;
      await route.fulfill({status:401,contentType:'application/json',body:JSON.stringify({detail:'Simulated expired access'})});
    } else await route.continue();
  });
  await page.getByRole('button',{name:'Simpan pencatatan',exact:true}).click();
  await page.getByRole('button',{name:'Coba ulang penyimpanan',exact:true}).waitFor();
  await page.reload();
  await login(admin);
  await page.getByRole('heading',{name:'Konfirmasi pencatatan sebelumnya'}).waitFor();
  const originalPending = await page.evaluate(() => Object.keys(sessionStorage).filter(key=>key.startsWith('beeloft.pending.')).map(key=>sessionStorage.getItem(key)));
  await page.getByRole('button',{name:'Coba ulang penyimpanan',exact:true}).click();
  await page.getByRole('button',{name:'Masuk ulang',exact:true}).waitFor();
  const retainedPending = await page.evaluate(() => Object.keys(sessionStorage).filter(key=>key.startsWith('beeloft.pending.')).map(key=>sessionStorage.getItem(key)));
  assert.equal(JSON.parse(originalPending[0]).transaction.key,JSON.parse(retainedPending[0]).transaction.key);
  await page.getByRole('button',{name:'Masuk ulang',exact:true}).click();
  await login(admin);
  await page.getByRole('heading',{name:'Konfirmasi pencatatan sebelumnya'}).waitFor();
  await page.getByRole('button',{name:'Coba ulang penyimpanan',exact:true}).click();
  await page.locator('dialog').waitFor({state:'hidden'});
  const movements = await apiGet('/api/orders/'+orderId+'/movements');
  assert.equal(movements.length,1);
  assert.equal((await apiGet('/api/orders/'+orderId)).totals.cutting,10);
  await page.getByRole('button',{name:new RegExp('DEMO-UI-ORDER-'+unique)}).click();
  await page.getByRole('button',{name:'Koreksi',exact:true}).click();
  await page.getByLabel('Alasan koreksi',{exact:true}).fill('CONTOH koreksi input');
  await page.getByRole('button',{name:'Simpan pencatatan',exact:true}).click();
  await page.locator('dialog').waitFor({state:'hidden'});
  await page.getByText('Sudah dibalik',{exact:false}).waitFor();
  assert.equal((await apiGet('/api/orders/'+orderId)).totals.planned,50);

  await page.getByRole('button',{name:'Catat kendala',exact:true}).first().click();
  await page.getByLabel('Tahap yang terkendala').selectOption('sewing');
  await page.getByLabel('PIC kendala').selectOption(creds.users[1].id);
  await page.getByLabel('Apa kendalanya?').fill('Jarum <rusak> & menunggu pengganti');
  await page.getByRole('button',{name:'Simpan pencatatan',exact:true}).click();
  await page.getByRole('heading',{name:'Kendala produksi · 1 terbuka',exact:true}).waitFor();
  assert.equal(await page.locator('.issue-item .reason').first().innerText(),'Jarum <rusak> & menunggu pengganti');
  await page.getByRole('button',{name:'Semua order',exact:false}).click();
  await page.locator('#issues-summary').click();
  await page.waitForFunction(() => document.getElementById('status').value === 'blocked' && !document.getElementById('order-list').hidden && document.querySelectorAll('.order-row').length === 1);
  await page.getByRole('button',{name:new RegExp('DEMO-UI-ORDER-'+unique)}).click();
  await page.getByRole('button',{name:'Selesaikan kendala',exact:true}).click();
  await page.getByLabel('Tindakan penyelesaian').fill('Jarum diganti, mesin diuji');
  await page.getByRole('button',{name:'Simpan pencatatan',exact:true}).click();
  await page.getByRole('heading',{name:'Kendala produksi · 0 terbuka',exact:true}).waitFor();
  await page.getByText('Jarum diganti, mesin diuji',{exact:true}).waitFor();
  assert.equal((await apiGet('/api/orders/'+orderId)).totals.planned,50);
  assert.equal((await apiGet('/api/orders/'+orderId+'/issues')).length,1);

  await page.getByRole('button',{name:'Ubah tenggat / PIC',exact:true}).click();
  assert.equal(await page.getByLabel('Target selesai baru').inputValue(),'2099-01-01');
  await page.getByLabel('Target selesai baru').fill('2099-02-01');
  await page.locator('dialog').getByLabel('PIC order',{exact:true}).selectOption(creds.users[1].id);
  await page.getByLabel('Alasan perubahan').fill('Mesin <dipindah> & jadwal diperbarui');
  await page.getByRole('button',{name:'Simpan pencatatan',exact:true}).click();
  await page.locator('dialog').waitFor({state:'hidden'});
  await page.locator('.detail-meta').getByText('1 Feb 2099',{exact:true}).waitFor();
  const revised = await apiGet('/api/orders/'+orderId);
  assert.equal(revised.owner_id,creds.users[1].id);
  assert.equal(revised.totals.planned,50);
  await page.getByRole('button',{name:'Riwayat tenggat / PIC',exact:true}).click();
  await page.getByText('Mesin <dipindah> & jadwal diperbarui',{exact:true}).waitFor();
  assert.equal(await page.locator('#order-change-list .issue-item').count(),1);
  await page.getByRole('button',{name:'Tutup dialog',exact:true}).click();
  await page.getByRole('button',{name:'Ubah tenggat / PIC',exact:true}).click();
  const otherEdit = await fetch(base+'/api/orders/'+orderId+'/changes',{method:'POST',headers:{
    'X-API-Key':admin,'Idempotency-Key':'concurrent-browser-edit','Content-Type':'application/json'},
    body:JSON.stringify({owner_id:revised.owner_id,due_date:'2099-03-01',expected_revision:revised.revision,reason:'Perubahan dari tab lain'})});
  assert.equal(otherEdit.status,201);
  await page.getByLabel('Target selesai baru').fill('2099-04-01');
  await page.getByLabel('Alasan perubahan').fill('Draft lama');
  await page.getByRole('button',{name:'Simpan pencatatan',exact:true}).click();
  await page.getByText('Jadwal atau PIC sudah diubah.',{exact:false}).waitFor();
  assert.equal((await apiGet('/api/orders/'+orderId)).due_date,'2099-03-01');
  await page.getByRole('button',{name:'Tutup dialog',exact:true}).click();
  await page.getByRole('button',{name:'Muat ulang order',exact:true}).click();
  await page.locator('.detail-meta').getByText('1 Mar 2099',{exact:true}).waitFor();

  await page.getByRole('button',{name:'Semua order',exact:false}).click();
  await page.getByLabel('Status',{exact:true}).selectOption('all');
  await page.getByRole('button',{name:/DEMO-PROD-001/}).click();
  await page.getByRole('heading',{name:'Posisi barang sekarang'}).waitFor();
  await page.evaluate(()=>document.getElementById('notice').hidden=true);
  await page.screenshot({path:path.join(work,'dashboard-detail.png'),fullPage:true});
  await page.getByRole('button',{name:'Mode gelap',exact:true}).click();
  await page.screenshot({path:path.join(work,'dashboard-dark.png'),fullPage:true});
  await page.setViewportSize({width:390,height:844});
  await page.screenshot({path:path.join(work,'dashboard-mobile.png'),fullPage:true});
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth),true);
  for (const width of [320,768,1440]) {
    await page.setViewportSize({width,height:900});
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth),true,'Overflow at '+width);
  }
  await page.setViewportSize({width:390,height:844});
  await page.evaluate(()=>document.documentElement.style.fontSize='200%');
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth),true,'Overflow at 200% text');
  await page.evaluate(()=>document.documentElement.style.fontSize='');
  await page.getByRole('button',{name:'Catat perpindahan',exact:true}).first().click();
  await page.keyboard.press('Escape');
  await page.locator('dialog').waitFor({state:'hidden'});
  await page.getByRole('button',{name:'Keluar',exact:true}).click();
  await login(viewer);
  assert.equal(await page.getByRole('button',{name:'Cadangan data',exact:true}).isVisible(),false);
  assert.equal(await page.getByRole('button',{name:'Buat order produksi',exact:true}).isVisible(),false);
  await page.getByRole('button',{name:/DEMO-PROD-001/}).click();
  await page.getByRole('heading',{name:'Posisi barang sekarang'}).waitFor();
  assert.equal(await page.getByRole('button',{name:'Catat perpindahan',exact:true}).count(),0);
  assert.equal(await page.getByRole('button',{name:'Koreksi',exact:true}).count(),0);
  assert.equal(await page.getByRole('button',{name:'Catat kendala',exact:true}).count(),0);
  assert.equal(await page.getByRole('button',{name:'Selesaikan kendala',exact:true}).count(),0);
  assert.equal(await page.getByRole('button',{name:'Ubah tenggat / PIC',exact:true}).count(),0);
  await page.getByRole('button',{name:'Keluar',exact:true}).click();
  await login(operator);
  assert.equal(await page.getByRole('button',{name:'Cadangan data',exact:true}).isVisible(),false);
  await page.getByRole('button',{name:/DEMO-PROD-001/}).click();
  await page.getByRole('button',{name:'Catat perpindahan',exact:true}).waitFor();
  assert.equal(await page.getByRole('button',{name:'Ubah tenggat / PIC',exact:true}).count(),0);
  assert.equal(await page.getByRole('button',{name:'Koreksi',exact:true}).count(),0);
  await page.getByRole('button',{name:'Laporan aktivitas',exact:true}).click();
  await page.locator('#activity-list .activity-item').first().waitFor();
  const reportDay = await page.getByLabel('Dari tanggal').inputValue();
  assert.ok(reportDay);
  await page.getByLabel('Jenis aktivitas').selectOption('order_changed');
  await page.waitForFunction(() => document.querySelectorAll('#activity-list .activity-item').length === 2);
  await page.locator('#activity-list').getByText('Mesin <dipindah> & jadwal diperbarui',{exact:true}).waitFor();
  const downloadPromise = page.waitForEvent('download');
  await page.getByRole('button',{name:'Unduh CSV',exact:true}).click();
  const download = await downloadPromise;
  assert.equal(download.suggestedFilename(),`beeloft-aktivitas-${reportDay}-${reportDay}-order_changed.csv`);
  const csvText = fs.readFileSync(await download.path(),'utf8');
  assert.ok(csvText.startsWith('\ufeffID kejadian,'));
  assert.ok(csvText.includes('Mesin <dipindah> & jadwal diperbarui'));
  assert.ok(!csvText.includes(admin));
  const activity = await apiGet('/api/activity?day='+reportDay+'&kind=order_changed');
  assert.equal(activity.total,2);
  assert.equal(await page.locator('#activity-summary dd').first().innerText(),activity.summary.events+' catatan');
  await page.setViewportSize({width:390,height:844});
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth),true,'Activity overflow');
  await page.screenshot({path:path.join(work,'activity-mobile.png'),fullPage:true});
  await page.getByLabel('Dari tanggal').fill('2000-01-01');
  await page.getByLabel('Sampai tanggal').fill('2000-01-01');
  await page.getByRole('button',{name:'Tampilkan aktivitas',exact:true}).click();
  await page.getByText('Tidak ada aktivitas yang cocok pada rentang ini.',{exact:true}).waitFor();
  assert.equal(await page.locator('#activity-list .activity-item').count(),0);
  await page.getByLabel('Dari tanggal').fill(reportDay);
  await page.getByLabel('Sampai tanggal').fill(reportDay);
  await page.getByRole('button',{name:'Tampilkan aktivitas',exact:true}).click();
  await page.locator('#activity-list .activity-item').first().waitFor();
  await page.locator('#activity-list').getByRole('button',{name:new RegExp('DEMO-UI-ORDER-'+unique)}).first().click();
  await page.getByRole('heading',{name:'CONTOH - Uji dashboard '+unique,exact:true}).waitFor();
  await page.getByRole('button',{name:'Keluar',exact:true}).click();
  await login(viewer);
  assert.equal(await page.getByRole('button',{name:'Cadangan data',exact:true}).isVisible(),false);
  await page.getByRole('button',{name:'Laporan aktivitas',exact:true}).click();
  await page.locator('#activity-list .activity-item').first().waitFor();
  assert.equal(await page.locator('#activity-view [data-action="move"]').count(),0);
  await require('./browser_materials.cjs')({page,login,admin,operator,viewer,apiGet,work});
  await require('./browser_bom.cjs')({page,login,admin,viewer,apiGet,work});
  await require('./browser_reservations.cjs')({page,login,admin,operator,viewer,apiGet,work});
  await require('./browser_consumption.cjs')({page,login,admin,operator,viewer,apiGet,work});
  await require('./browser_purchase_requests.cjs')({page,login,admin,operator,viewer,apiGet,work});
  await require('./browser_purchase_orders.cjs')({page,login,admin,operator,viewer,apiGet,work});
  await require('./browser_po_receipts.cjs')({page,login,admin,operator,viewer,apiGet,work});
  await require('./browser_incoming_qc.cjs')({page,login,admin,operator,viewer,apiGet,work});
  await require('./browser_supplier_returns.cjs')({page,login,admin,operator,viewer,apiGet,work});
  await require('./browser_supplier_payments.cjs')({page,login,admin,operator,viewer,apiGet,work});
  await require('./browser_marketing_budgets.cjs')({page,login,admin,operator,viewer,apiGet,work});
  const productionCost=await require('./browser_production_cost.cjs')({page,login,admin,viewer,apiGet,work});
  await require('./browser_contribution_margin.cjs')({page,login,admin,operator,viewer,apiGet,work,...productionCost});
  await require('./browser_demand_forecast.cjs')({page,login,viewer,apiGet,work});
  await require('./browser_replenishment_recommendations.cjs')({page,login,admin,viewer,apiGet,work,...productionCost});
  await require('./browser_integrations.cjs')({page,login,admin,operator,viewer,apiGet,apiPost,work});
  await require('./browser_product_external_mappings.cjs')({page,login,admin,viewer,apiGet,work});
  await require('./browser_jubelio_stock_snapshots.cjs')({page,login,viewer,apiGet,apiPost,work});
  await require('./browser_jubelio_order_snapshots.cjs')({page,login,viewer,apiGet,apiPost,work});
  await require('./browser_jubelio_return_snapshots.cjs')({page,login,viewer,apiGet,apiPost,work});
  await require('./browser_ai_investigation.cjs')({page,login,admin,operator,viewer,apiGet,work});
  await require('./browser_cutting.cjs')({page,login,admin,operator,viewer,apiGet,work});
  await require('./browser_bundles.cjs')({page,login,admin,operator,viewer,apiGet,work});
  await require('./browser_sewing.cjs')({page,login,admin,operator,viewer,apiGet,work});
  await require('./browser_finishing.cjs')({page,login,admin,operator,viewer,apiGet,work});
  await require('./browser_final_qc.cjs')({page,login,admin,operator,viewer,apiGet,work});
  const finishedGoods=await require('./browser_finished_goods.cjs')({page,login,admin,operator,viewer,apiGet,work});
  await require('./browser_warehouse_movements.cjs')({page,login,admin,operator,viewer,apiGet,work,...finishedGoods});
  const marketplace=await require('./browser_marketplace_reservations.cjs')({page,login,admin,operator,viewer,apiGet,work,...finishedGoods});
  const picking=await require('./browser_marketplace_picking.cjs')({page,login,admin,operator,viewer,apiGet,work,...finishedGoods,...marketplace});
  const packing=await require('./browser_marketplace_packing.cjs')({page,login,admin,operator,viewer,apiGet,work,...finishedGoods,...marketplace,...picking});
  const shipping=await require('./browser_marketplace_shipping.cjs')({page,login,admin,operator,viewer,apiGet,work,...finishedGoods,...marketplace,...picking,...packing});
  await require('./browser_returns_adjustments.cjs')({page,login,admin,operator,viewer,apiGet,work,...finishedGoods,...shipping});
  await require('./browser_inventory_reconciliation.cjs')({page,login,admin,operator,viewer,apiGet,work,...finishedGoods});
  await require('./browser_unified_approvals.cjs')({page,login,admin,operator,viewer,apiGet,work,...finishedGoods});
  assert.deepEqual(errors,[]);
  await browser.close();
  console.log('Browser QA PASS: login, filters, SKU, multi-SKU order, partial move, lost-response reload/retry exactly once, reversal, roles, dark theme, mobile overflow, Escape; no JS errors.');
})().catch(error => {console.error(error);process.exit(1);});
